### ISSUE TITLE
Table element

### ISSUE THREAD

**Issue by nguyenLisa** [gapran/prototypeJS#9]
See https://github.com/gapran/sim_platform/issues/4

**Comment by rashmigupta1709** [comment]
Table is present inside client/imports/ui/table folder . 

Only the header name is to be given and data could be retrieved from Database or mapped however required.

**Comment by ghost** [comment]
I am able to visualize the **headers** provided by _user_. Alternatively, has a solution to render headers data from MongoDB. However, with present understanding I notice there is a hindrance in context of table body data that has to be retrieved from database based on the ( multiple ) **key** names of respective _documents_ in a _collection_. 

Here's the sample output for better understanding.

In a process of showing the data from MongoDB onto UI, I am using _Spacebars_ templates. 

- Double-braced template tags renders the data using keys ( Example: {{name}} -> project name ). 

https://github.com/gapran/prototypeJS/blob/3230b814248dfc0182e8928b856428eb443f6c6b/imports/ui/table/table.html#L26-L33
https://github.com/gapran/prototypeJS/blob/3230b814248dfc0182e8928b856428eb443f6c6b/imports/ui/table/table.js#L25-L32

![double braced template](https://user-images.githubusercontent.com/17321286/59396546-974db900-8d89-11e9-9329-90cb52def822.jpg)

- Triple-braced template tags are used to insert raw HTML.

![triple braced template](https://user-images.githubusercontent.com/17321286/59396561-a9c7f280-8d89-11e9-8ba3-cf4b54dc3b8a.jpg)

Neither of them is serving the scenario of showing the data provided at _body.html_  with template parameters. 

https://github.com/gapran/prototypeJS/blob/3230b814248dfc0182e8928b856428eb443f6c6b/imports/ui/prototype1/body.html#L21


###### **Reference**: http://blazejs.org/api/spacebars.html

**Comment by nguyenLisa** [comment]
Use `this.keyNames` to have access to your keyNames array in the helpers. You can then iterate through it as shown in https://github.com/gapran/prototypeJS/blob/develop/imports/ui/tabs/tabs.js#L19

**Comment by ghost** [comment]
Thank you for the suggestion. The `keyNames` are retrievable as you suggested and succeeded with it at 7be20ebc5f137708903c4206ca2acee1091b4547.  The concern is that, generated _spacebars_ using _helpers_ ( `{{renderKeysHTML}}`  ) for accessing database is not working unless respective key names are hard coded as illustrated above. 

Please let me know if am not clear in explaining the issue.

**Comment by nguyenLisa** [comment]
I'm not sure I understand. Why do you need the `keyNames` to be retrieved from the dabatase? In case you need them, is it possible to create a function `retrieveKeyNames` in the helper, that queries the database, and returns those names? This function can then be called from the html template.

**Comment by rashmigupta1709** [comment]
are you trying to retrieve the header names from database or the value of the header names ? In case, if you are trying to retrieve the headers from database so that you can create multiple tables with same number of columns , please let me know OR you will have to create a different collection in database, get the value from this headerDBCollection and get the values of those headers from another database, but I am not sure why you would want to do that.

In case if you want to change the names of the header, go to table.html file, i have attached an example of how to show static data and data to be retrieved from database using template.

Even for using template, there are multiple examples used within the project, check out progressbar.html and progressbar.js , using a template, i am returning the value of just one field, now if you want to get this value from mongo db , use db.collectionName.findOne("query") .

Similarly, if you want to retrieve the values of headers, create a template , call the function using
     ----{{> selectedHeaders}}

    ----<template name = "selectedHeaders">{{col1}}{{col2}}.......etc.</template>----

   ---- Using Template.selectedHeaders.helpers({
                    col1 : function(){ return ;},
                    col2 : function(){ return ;}
                    });

Write a template for selectedHeaders and then try retrieving these col1,col2 ... values from the database , and then you can map these local col1,col2 ... variables to dynamically load your table.

In case, if it helps : )

**Comment by ghost** [comment]
Thank you for detailed comment. 
With your example in relation to the issue mentioned, 
`----<template name = "selectedHeaders">{{col1}}{{col2}}.......etc.</template>----` 
I am trying to render `{{col1}} {{col2}}` which are user given and their values same time without hard coding the column names in _table_ library.

https://github.com/gapran/prototypeJS/blob/3230b814248dfc0182e8928b856428eb443f6c6b/imports/ui/table/table.html#L26-L33

**Comment by ghost** [comment]
As it is decided to have hard coded column names to retrieve values from database, 
here is the latest output ( 1d8effb81b25e4a290534c65885c932960e56ed8 ) for this issue #9. 
+ Sorting 
+ Scroll

![table](https://user-images.githubusercontent.com/17321286/59684830-1f452000-91db-11e9-906e-739a992b41d7.jpg)

**Comment by nguyenLisa** [comment]
0f3d189fca7be256ae84fb5f7a641aeff0c67c18
